# Generated by Django 6.0.5 on 2026-05-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.deployment')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.guard')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guard_schedules', to='core.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guard_schedules', to='core.site')),
            ],
            options={
                'ordering': ['shift_date', 'shift__start_time', 'guard__employee__first_name'],
                'unique_together': {('deployment', 'shift_date')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='core.guardschedule'),
        ),
    ]
