# Generated by Django 6.0.5 on 2026-05-15 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_access_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ["Human Resources Manager", "Supervisor", "Guard"]:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_site_options_site_site_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_code', models.CharField(max_length=30, unique=True)),
                ('zone_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('closed', 'Closed')], default='active', max_length=20)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='core.supervisor')),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='ZoneGuardAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('closed', 'Closed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_zone_allocations', to=settings.AUTH_USER_MODEL)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_allocations', to='core.guard')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_allocations', to='core.zone')),
            ],
            options={
                'ordering': ['zone', 'guard__employee__first_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('status', 'active')), fields=('guard',), name='unique_active_guard_zone')],
            },
        ),
        migrations.CreateModel(
            name='ZoneSiteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('closed', 'Closed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_zone_allocations', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_allocations', to='core.site')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_allocations', to='core.zone')),
            ],
            options={
                'ordering': ['zone', 'site__site_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('status', 'active')), fields=('site',), name='unique_active_site_zone')],
            },
        ),
        migrations.RunPython(create_access_groups, migrations.RunPython.noop),
    ]
