# Generated by Django 6.0.5 on 2026-05-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_badge_number_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField('NSSF number', blank=True, max_length=80, null=True, unique=True),
        ),
    ]
