# Generated by Django 6.0.5 on 2026-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_nssf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='attendance_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='basic_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='nssf_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='nssf_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
