# Generated by Django 6.0.5 on 2026-05-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_salary_attendance_days_salary_basic_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
