# Generated by Django 6.0.5 on 2026-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_invoice_billing_month_invoice_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsiterequirement',
            name='dog_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='dog_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='gun_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='gun_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='metal_detector_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='metal_detector_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='radio_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='radio_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='rate_per_guard',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 to use the parent contract billing rate.', max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='walk_through_machine_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='walk_through_machine_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_scope',
            field=models.CharField(choices=[('site', 'One Site'), ('contract', 'All Contract Sites')], default='site', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
