# Generated by Django 6.0.5 on 2026-05-20 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contractsiterequirement_dog_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='action_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='training',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trainings', to='core.employee'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_file',
            field=models.FileField(blank=True, upload_to='training_certificates/'),
        ),
        migrations.AddField(
            model_name='training',
            name='course_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='training',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='training',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='next_refresh_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='pass_mark',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='training',
            name='result',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='scheduled', max_length=30),
        ),
        migrations.AddField(
            model_name='training',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer_contact',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='training',
            name='training_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='training',
            name='training_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('induction', 'Induction'), ('refresher', 'Refresher'), ('compliance', 'Compliance'), ('fire_safety', 'Fire Safety'), ('first_aid', 'First Aid'), ('customer_care', 'Customer Care'), ('supervisory', 'Supervisory'), ('firearms', 'Firearms'), ('radio_communication', 'Radio Communication'), ('site_procedures', 'Site Procedures')], default='induction', max_length=40),
        ),
        migrations.AddField(
            model_name='training',
            name='venue',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
