# Generated by Django 6.0.5 on 2026-05-20 06:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_training_action_notes_training_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('application_source', models.CharField(choices=[('physical', 'Physical Walk-in'), ('online', 'Online Application'), ('referral', 'Employee Referral'), ('agency', 'Recruitment Agency'), ('job_board', 'Job Board')], default='physical', max_length=30)),
                ('date_received', models.DateField(default=django.utils.timezone.localdate)),
                ('online_profile_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, upload_to='recruitment_cvs/')),
                ('application_form_file', models.FileField(blank=True, upload_to='recruitment_forms/')),
                ('highest_qualification', models.CharField(blank=True, max_length=180)),
                ('years_experience', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_employer', models.CharField(blank=True, max_length=150)),
                ('expected_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('screening_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('police_clearance_no', models.CharField(blank=True, max_length=100)),
                ('background_check_status', models.CharField(blank=True, max_length=80)),
                ('medical_check_status', models.CharField(blank=True, max_length=80)),
                ('reference_check_status', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('received', 'Received'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('background_check', 'Background Check'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_received', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('salary_offer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, upload_to='offer_letters/')),
                ('notes', models.TextField(blank=True)),
                ('offered_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to='core.position')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer', to='core.recruitmentapplication')),
            ],
            options={
                'ordering': ['-offer_date', 'application'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('online', 'Online'), ('physical', 'Physical'), ('panel', 'Panel'), ('practical', 'Practical Assessment')], default='physical', max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('venue_or_link', models.CharField(blank=True, max_length=220)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('recommendation', models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('hold', 'Hold'), ('not_recommended', 'Not Recommended')], default='pending', max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.recruitmentapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews', to='core.employee')),
            ],
            options={
                'ordering': ['-scheduled_at', 'application'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_number', models.CharField(max_length=80, unique=True)),
                ('vacancy_title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('operations', 'Operations'), ('human_resource', 'Human Resource'), ('finance', 'Finance'), ('admin', 'Admin')], max_length=30)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('casual', 'Casual'), ('internship', 'Internship')], default='full_time', max_length=30)),
                ('work_location', models.CharField(blank=True, max_length=150)),
                ('opening_date', models.DateField(default=django.utils.timezone.localdate)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('salary_budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary_budget_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_qualification', models.CharField(blank=True, max_length=180)),
                ('experience_required', models.CharField(blank=True, max_length=150)),
                ('job_description', models.TextField(blank=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('shortlisting', 'Shortlisting'), ('interviewing', 'Interviewing'), ('offering', 'Offering'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='core.position')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requisitions', to='core.employee')),
            ],
            options={
                'ordering': ['-opening_date', 'requisition_number'],
            },
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.recruitmentrequisition'),
        ),
    ]
