# Generated by Django 6.0.5 on 2026-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recruitmentapplication_joboffer_recruitmentinterview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequisition',
            name='actual_recruitment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recruitmentrequisition',
            name='recruitment_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='training',
            name='budgeted_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
