# Generated by Django 6.0.5 on 2026-05-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_employee_obsolete_guard_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinaryaction',
            options={'ordering': ['-action_date'], 'verbose_name': 'Disciplinary action', 'verbose_name_plural': 'Disciplinary actions'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['employee', 'doc_type'], 'verbose_name': 'Employee document', 'verbose_name_plural': 'Employee documents'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-offer_date', 'application'], 'verbose_name': 'Job offer', 'verbose_name_plural': 'Job offers'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date', 'reference'], 'verbose_name': 'Journal entry', 'verbose_name_plural': 'Journal entries'},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['journal_entry__entry_date', 'journal_entry__reference', 'id'], 'verbose_name': 'Journal line', 'verbose_name_plural': 'Journal lines'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Leave request', 'verbose_name_plural': 'Leave requests'},
        ),
        migrations.AlterModelOptions(
            name='performanceevaluation',
            options={'ordering': ['-eval_date'], 'verbose_name': 'Performance evaluation', 'verbose_name_plural': 'Performance evaluations'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentapplication',
            options={'ordering': ['-date_received', 'last_name', 'first_name'], 'verbose_name': 'Recruitment application', 'verbose_name_plural': 'Recruitment applications'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentinterview',
            options={'ordering': ['-scheduled_at', 'application'], 'verbose_name': 'Recruitment interview', 'verbose_name_plural': 'Recruitment interviews'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentrequisition',
            options={'ordering': ['-opening_date', 'requisition_number'], 'verbose_name': 'Recruitment requisition', 'verbose_name_plural': 'Recruitment requisitions'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-pay_period_start', 'employee'], 'verbose_name': 'Salary', 'verbose_name_plural': 'Salaries'},
        ),
    ]
