# Generated by Django 6.0.5 on 2026-05-25 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_disciplinaryaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_reference', models.CharField(db_index=True, default=uuid.uuid4, max_length=36)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(choices=[('simple', 'Simple Excel'), ('saracen', 'Saracen Excel')], default='simple', max_length=20)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('shift_date', models.DateField(blank=True, null=True)),
                ('duty_code', models.CharField(blank=True, max_length=40)),
                ('import_status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped')], default='created', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_attendances', to='core.employee')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_attendances', to='core.guardschedule')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_attendances', to='core.shift')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_attendances', to='core.site')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_upload_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roster attendance',
                'verbose_name_plural': 'Roster attendances',
                'ordering': ['-created_at', 'shift_date', 'site__site_name', 'employee__first_name'],
            },
        ),
    ]
