# Generated by Django 6.0.5 on 2026-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rosterattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterattendance',
            name='import_status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('off', 'Off')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='rosterattendance',
            name='source_format',
            field=models.CharField(choices=[('simple', 'Simple Excel'), ('saracen', 'Saracen Excel'), ('wide_monthly', 'Wide Monthly Excel')], default='simple', max_length=20),
        ),
    ]
