# Generated by Django 6.0.5 on 2026-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_rosterattendance_import_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dog_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='handcuffs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='metal_detector_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='panic_baton_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='walk_through_detector_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_type',
            field=models.CharField(choices=[('Manned Guarding', 'Manned Guarding'), ('Site Supervision', 'Site Supervision'), ('Incident Management', 'Incident Management'), ('Workforce Control', 'Workforce Control'), ('Others', 'Others')], default='Manned Guarding', max_length=120),
        ),
    ]
