# Generated by Django 6.0.5 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_contract_dog_count_contract_handcuffs_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dog_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='handcuffs_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='metal_detector_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='panic_baton_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='walk_through_detector_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
