# Generated by Django 6.0.5 on 2026-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contract_dog_rate_contract_handcuffs_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsiterequirement',
            name='handcuffs_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='handcuffs_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='panic_baton_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractsiterequirement',
            name='panic_baton_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
