# Generated by Django 6.0.5 on 2026-05-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contractsiterequirement_handcuffs_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='selected_sites',
            field=models.ManyToManyField(blank=True, related_name='multi_site_invoices', to='core.site'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_scope',
            field=models.CharField(choices=[('site', 'One Site'), ('multiple_sites', 'Selected Sites'), ('contract', 'All Contract Sites')], default='site', max_length=20),
        ),
    ]
