# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


def copy_schedule_site_to_attendance(apps, schema_editor):
    Attendance = apps.get_model("core", "Attendance")
    for attendance in Attendance.objects.select_related("schedule").filter(site__isnull=True, schedule__isnull=False):
        attendance.site_id = attendance.schedule.site_id
        attendance.save(update_fields=["site"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_invoice_selected_sites_alter_invoice_billing_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="core.site",
            ),
        ),
        migrations.RunPython(copy_schedule_site_to_attendance, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date", "shift", "site")},
        ),
    ]
