# Generated by Django 6.0.5 on 2026-06-02 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_subscriptionplan_tenantorganization_tenantmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_keen_contact',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'pay_period_start'), name='unique_employee_pay_period'),
        ),
    ]
