# Generated by Django 6.0.5 on 2026-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_client_client_name_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
