# Generated by Django 6.0.5 on 2026-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_salary_advance_balance_salary_advance_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_obligations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_representative',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_representative_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_representative_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_obligations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_representative',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_representative_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='confidentiality_clause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='governing_law',
            field=models.CharField(blank=True, default='Uganda', max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='guard_training_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='liability_limit',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='response_time_sla',
            field=models.CharField(blank=True, max_length=120, verbose_name='Response time SLA'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_location',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='special_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='supervision_frequency',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_notice_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
