# Generated by Django 6.0.5 on 2026-06-04 19:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_contract_billing_cycle_contract_client_obligations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amendment_document',
            field=models.FileField(blank=True, upload_to='contract_documents/amendments/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='annual_contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contract',
            name='arming_status',
            field=models.CharField(choices=[('unarmed', 'Unarmed'), ('armed', 'Armed'), ('mixed', 'Mixed')], default='unarmed', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_representative_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to='core.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('fixed_term', 'Fixed Term'), ('renewable', 'Renewable'), ('framework', 'Framework Contract'), ('one_time', 'One-Time Service')], default='fixed_term', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='day_guards_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='deployment_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.site'),
        ),
        migrations.AddField(
            model_name='contract',
            name='incident_escalation_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='late_payment_penalty',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contract',
            name='metal_detector_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contract',
            name='night_guards_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='patrol_frequency',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='patrol_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.CharField(choices=[('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('advance', 'Advance Payment'), ('custom', 'Custom')], default='net_30', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='radio_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_document',
            field=models.FileField(blank=True, upload_to='contract_documents/renewals/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_reminder_days',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_breach_penalty',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='contract',
            name='shift_pattern',
            field=models.CharField(blank=True, choices=[('8_hours', '8 Hours'), ('12_hours', '12 Hours'), ('24_hours', '24 Hours'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_contract',
            field=models.FileField(blank=True, upload_to='contract_documents/signed/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supervisors_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='torch_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='uniform_requirement',
            field=models.CharField(choices=[('company', 'Company Uniform'), ('client', 'Client Uniform'), ('both', 'Client and Company Uniform'), ('custom', 'Custom')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='vehicle_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD'), ('KES', 'KES'), ('TZS', 'TZS')], default='UGX', max_length=3),
        ),
    ]
