# Generated by Django 6.0.5 on 2026-06-04 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_contract_amendment_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='core.employee'),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('security_breach', 'Security Breach'), ('theft', 'Theft'), ('assault', 'Assault'), ('fire', 'Fire'), ('accident', 'Accident'), ('absenteeism', 'Guard Absenteeism'), ('client_complaint', 'Client Complaint'), ('property_damage', 'Property Damage'), ('medical', 'Medical Emergency'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='closure_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='corrective_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='estimated_loss_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='incident_evidence/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='follow_up_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='immediate_action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_reference',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='injury_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='management_action_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='management_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='management_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='management_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='police_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='police_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='incident',
            name='preventive_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='property_damage_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='witness_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Management'), ('under_review', 'Under Management Review'), ('action_required', 'Action Required'), ('awaiting_follow_up', 'Awaiting Follow-up'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
