# Generated by Django 6.0.5 on 2026-06-04 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_incident_action_taken_incident_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='accommodation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deployments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='armed_status',
            field=models.CharField(choices=[('unarmed', 'Unarmed'), ('armed', 'Armed'), ('mixed', 'Mixed')], default='unarmed', max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='attendance_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='baton_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='check_in_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='check_out_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='core.contract'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='contract_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='core.contractsiterequirement'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_reference',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('relief', 'Relief'), ('emergency', 'Emergency'), ('replacement', 'Replacement'), ('special_assignment', 'Special Assignment')], default='permanent', max_length=30),
        ),
        migrations.AddField(
            model_name='deployment',
            name='duty_post',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deployment',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deployment',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='deployment',
            name='firearm_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='handover_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='metal_detector_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='radio_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='reliever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_deployments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='reporting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='site_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deployment',
            name='site_contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deployment',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number using digits only, optionally starting with +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='deployment',
            name='site_role',
            field=models.CharField(choices=[('guard', 'Guard'), ('supervisor', 'Supervisor'), ('commander', 'Commander'), ('dog_handler', 'Dog Handler'), ('radio_operator', 'Radio Operator'), ('cctv_operator', 'CCTV Operator')], default='guard', max_length=30),
        ),
        migrations.AddField(
            model_name='deployment',
            name='torch_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='transport_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='uniform_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='vehicle_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
    ]
