"""
Django settings for security_management project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import shutil
import warnings
from pathlib import Path
from urllib.parse import parse_qsl, urlparse, unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_VERCEL = bool(os.environ.get("VERCEL") or os.environ.get("VERCEL_ENV") or os.environ.get("VERCEL_URL"))
DATABASE_RUNTIME_NOTE = ""


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=()):
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


def vercel_hosts():
    hosts = [
        "guard-management-erp.vercel.app",
        os.environ.get("VERCEL_URL"),
        os.environ.get("VERCEL_BRANCH_URL"),
        os.environ.get("VERCEL_PROJECT_PRODUCTION_URL"),
    ]
    return [host.replace("https://", "").replace("http://", "").strip("/") for host in hosts if host]


def https_origins(hosts):
    return [
        f"https://{host}"
        for host in hosts
        if host and not host.startswith(".") and host not in {"127.0.0.1", "localhost", "testserver"}
    ]


def database_from_url(url):
    parsed = urlparse(url)
    scheme = parsed.scheme.lower()
    if scheme in {"postgres", "postgresql"}:
        engine = "django.db.backends.postgresql"
    elif scheme == "sqlite":
        engine = "django.db.backends.sqlite3"
    else:
        raise ValueError(f"Unsupported database URL scheme: {parsed.scheme}")

    if engine == "django.db.backends.sqlite3":
        name = unquote(parsed.path.lstrip("/")) or str(BASE_DIR / "db.sqlite3")
        if parsed.netloc:
            name = f"//{parsed.netloc}/{name}"
        return sqlite_runtime_config({"ENGINE": engine, "NAME": name})

    options = dict(parse_qsl(parsed.query, keep_blank_values=True))
    config = {
        "ENGINE": engine,
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }
    if options:
        config["OPTIONS"] = options
    return config


def sqlite_runtime_config(config):
    global DATABASE_RUNTIME_NOTE
    if not IS_VERCEL or config.get("ENGINE") != "django.db.backends.sqlite3":
        return config

    configured_name = config.get("NAME")
    bundled_db = BASE_DIR / "db.sqlite3"
    writable_db = Path(os.environ.get("DJANGO_SQLITE_TMP_NAME", "/tmp/erp.sqlite3"))
    try:
        writable_db.parent.mkdir(parents=True, exist_ok=True)
        if configured_name:
            configured_db = Path(configured_name)
            if configured_db.exists():
                bundled_db = configured_db
        if bundled_db.exists() and not writable_db.exists():
            shutil.copy2(bundled_db, writable_db)
        DATABASE_RUNTIME_NOTE = (
            "Using writable /tmp SQLite fallback for Vercel. "
            "This avoids read-only errors but is not durable production storage. "
            "Use DATABASE_URL or POSTGRES_URL with PostgreSQL for permanent production data."
        )
        updated = dict(config)
        updated.update(
            {
                "NAME": str(writable_db),
                "USER": "",
                "PASSWORD": "",
                "HOST": "",
                "PORT": "",
            }
        )
        return updated
    except OSError as error:
        warnings.warn(f"Could not prepare writable SQLite fallback: {error}", RuntimeWarning)
        return config


def database_config():
    global DATABASE_RUNTIME_NOTE
    database_url = (
        os.environ.get("DATABASE_URL")
        or os.environ.get("POSTGRES_URL")
        or os.environ.get("POSTGRES_URL_NON_POOLING")
        or os.environ.get("POSTGRES_PRISMA_URL")
    )
    if database_url:
        return database_from_url(database_url)

    engine = os.environ.get("DJANGO_DB_ENGINE", "django.db.backends.sqlite3")
    configured_name = os.environ.get("DJANGO_DB_NAME")
    return sqlite_runtime_config({
        "ENGINE": engine,
        "NAME": configured_name or str(BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DJANGO_DB_USER", ""),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", ""),
        "HOST": os.environ.get("DJANGO_DB_HOST", ""),
        "PORT": os.environ.get("DJANGO_DB_PORT", ""),
    })


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY") or "dev-only-insecure-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=not IS_VERCEL)

DEFAULT_ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver", ".vercel.app", *vercel_hosts()]
ALLOWED_HOSTS = sorted(set(DEFAULT_ALLOWED_HOSTS + env_list("DJANGO_ALLOWED_HOSTS")))
CSRF_TRUSTED_ORIGINS = sorted(
    set(["https://*.vercel.app", *https_origins(ALLOWED_HOSTS), *env_list("DJANGO_CSRF_TRUSTED_ORIGINS")])
)

if not DEBUG and SECRET_KEY == "dev-only-insecure-change-me":
    warnings.warn(
        "DJANGO_SECRET_KEY or SECRET_KEY is not set while DJANGO_DEBUG is false. "
        "Set a long random secret in the deployment environment before using this app with real data.",
        RuntimeWarning,
    )


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.DatabaseErrorMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'security_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.sidebar_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'security_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {"default": database_config()}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "core.auth_backends.EnvSuperuserBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_USE_FINDERS = True
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
if IS_VERCEL:
    SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
DISABLE_LAST_LOGIN_UPDATE = env_bool("DJANGO_DISABLE_LAST_LOGIN_UPDATE", default=IS_VERCEL)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)

FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", 5 * 1024 * 1024))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", 10 * 1024 * 1024))
MAX_UPLOAD_SIZE = int(os.environ.get("DJANGO_MAX_UPLOAD_SIZE", 5 * 1024 * 1024))
MAX_EXCEL_UPLOAD_SIZE = int(os.environ.get("DJANGO_MAX_EXCEL_UPLOAD_SIZE", 5 * 1024 * 1024))
ATTENDANCE_API_MAX_BODY_BYTES = int(os.environ.get("ATTENDANCE_API_MAX_BODY_BYTES", 32 * 1024))

JAZZMIN_SETTINGS = {
    "site_title": "Sentinel ERP Admin",
    "site_header": "Sentinel ERP",
    "site_brand": "Sentinel ERP",
    "welcome_sign": "Security Operations Administration",
    "copyright": "Security Company",
    "site_logo": None,
    "login_logo": None,
    "site_icon": None,
    "custom_css": "core/admin.css",
    "show_ui_builder": False,
    "show_theme_chooser": False,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "core.Client",
        "core.Contract",
        "core.ContractSiteRequirement",
        "core.Site",
        "core.Shift",
        "core.Deployment",
        "core.GuardSchedule",
        "core.RosterAttendance",
        "core.Attendance",
        "core.Employee",
        "core.Salary",
        "core.Invoice",
        "core.Payment",
        "core.Account",
        "core.JournalEntry",
        "core.JournalLine",
        "auth.User",
        "auth.Group",
    ],
    "topmenu_links": [
        {"name": "ERP Dashboard", "url": "core:dashboard", "permissions": ["auth.view_user"]},
        {"name": "Public Site", "url": "core:home"},
    ],
    "custom_links": {
        "core": [
            {"name": "Attendance Console", "url": "core:attendances", "icon": "fas fa-calendar-check"},
            {"name": "Reports Center", "url": "core:reports_center", "icon": "fas fa-folder-open"},
            {"name": "Payroll", "url": "core:payroll", "icon": "fas fa-money-check-dollar"},
        ]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "core.Client": "fas fa-building",
        "core.Contract": "fas fa-file-signature",
        "core.ContractSiteRequirement": "fas fa-clipboard-list",
        "core.Site": "fas fa-location-dot",
        "core.Shift": "fas fa-clock",
        "core.Deployment": "fas fa-person-military-pointing",
        "core.GuardSchedule": "fas fa-calendar-check",
        "core.RosterAttendance": "fas fa-file-excel",
        "core.Incident": "fas fa-triangle-exclamation",
        "core.PatrolLog": "fas fa-route",
        "core.Asset": "fas fa-boxes-stacked",
        "core.Employee": "fas fa-id-card",
        "core.Role": "fas fa-user-tag",
        "core.Position": "fas fa-briefcase",
        "core.Zone": "fas fa-map-location-dot",
        "core.Attendance": "fas fa-clipboard-check",
        "core.AttendanceDevice": "fas fa-fingerprint",
        "core.Training": "fas fa-graduation-cap",
        "core.RecruitmentRequisition": "fas fa-bullhorn",
        "core.RecruitmentApplication": "fas fa-file-user",
        "core.RecruitmentInterview": "fas fa-comments",
        "core.JobOffer": "fas fa-handshake",
        "core.Salary": "fas fa-money-check-dollar",
        "core.Advance": "fas fa-hand-holding-dollar",
        "core.Invoice": "fas fa-file-invoice-dollar",
        "core.Payment": "fas fa-money-bill-transfer",
        "core.Account": "fas fa-book",
        "core.JournalEntry": "fas fa-scale-balanced",
        "core.JournalLine": "fas fa-list-check",
        "core.Budget": "fas fa-chart-pie",
        "core.Expense": "fas fa-receipt",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle-dot",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "core.employee": "collapsible",
        "core.training": "collapsible",
        "core.recruitmentapplication": "collapsible",
        "core.recruitmentrequisition": "collapsible",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_child_indent": True,
    "body_small_text": False,
    "brand_small_text": False,
    "footer_small_text": True,
    "theme": "litera",
    "default_theme_mode": "light",
    "accent": "accent-success",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
